[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
exercise_anchor = "4vzULsyMxjoaMGqNGzST3ema18rwuapDb7nZcVfhUtph"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yobel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
